name: Invsee
version: '${project.version}'
main: de.lexarox.invsee.Invsee
api-version: '1.20'
author: lexarox
description: Basic Invsee Plugin

commands:
  invsee:
    permission: invsee.use
  ec:
  clear:
    aliases:
      - ci
  drop:



permissions:
  invsee.use:
    default: op
  ec.use:
    default: true
  ec.others:
    default: op
  clear.use:
    default: true
  clear.others:
    default: op
  drop.use:
    default: true
  drop.others:
    default: op